### ISSUE TITLE
User name mismatch

### ISSUE THREAD

**Issue by tinvujasinovic** [rkgeronimo/wp-web#21]
When updating my OIB, I used the autofill option from Chrome which filled out the input field, but I didn't notice it put in my address saved within the autofill as my `first` and `last` name - now on some parts of the app my name is still displayed as the address even after updating it

<img src="https://github.com/rkgeronimo/wp-web/assets/37039349/8a92ea3b-2978-4d32-8704-a9ec2f480edb" width="200 /"> <br />
<img src="https://github.com/rkgeronimo/wp-web/assets/37039349/9ed35ae2-dd77-402b-bfef-ddfeec1685bc" width="200 /">
<br />
<img src="https://github.com/rkgeronimo/wp-web/assets/37039349/cd887716-8de6-413c-975c-50789c4b2fec" width="200 /">
<br />
<img src="https://github.com/rkgeronimo/wp-web/assets/37039349/4d380b82-e23f-49fc-94d1-7b2a4aba8b0d" width="200 /">

**Comment by morrigan** [comment]
@tinvujasinovic this is fixed now!
